package wsclient.com.accenture.avs.be.ws.getpricebyuserservice_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import wsclient.getpricebyuser.avs.accenture.ports.getpricebyuserservice_v1.GetPriceByUserPort;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.9-redhat-2
 * 2013-05-07T10:07:00.212+02:00
 * Generated source version: 2.4.9-redhat-2
 * 
 */
@WebServiceClient(name = "GetPriceByUserService", 
                  wsdlLocation = "file:/development/wsAccenture/AMS/WebContent/WEB-INF/wsdl/GetPriceByUser/AVS_GetPriceByUser_Service.wsdl",
                  targetNamespace = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1") 
public class GetPriceByUserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.be.avs.accenture.com/GetPriceByUserService-v1", "GetPriceByUserService");
    public final static QName GetPriceByUserServicePort = new QName("http://ws.be.avs.accenture.com/GetPriceByUserService-v1", "GetPriceByUserServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/development/wsAccenture/AMS/WebContent/WEB-INF/wsdl/GetPriceByUser/AVS_GetPriceByUser_Service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetPriceByUserService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/development/wsAccenture/AMS/WebContent/WEB-INF/wsdl/GetPriceByUser/AVS_GetPriceByUser_Service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetPriceByUserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetPriceByUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetPriceByUserService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns GetPriceByUserPort
     */
    @WebEndpoint(name = "GetPriceByUserServicePort")
    public GetPriceByUserPort getGetPriceByUserServicePort() {
        return super.getPort(GetPriceByUserServicePort, GetPriceByUserPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPriceByUserPort
     */
    @WebEndpoint(name = "GetPriceByUserServicePort")
    public GetPriceByUserPort getGetPriceByUserServicePort(WebServiceFeature... features) {
        return super.getPort(GetPriceByUserServicePort, GetPriceByUserPort.class, features);
    }

}
