
package com.accenture.ams.pkgingestor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PackageIngestorPort", targetNamespace = "http://ports.accenture.avs.packageingestor/PackageIngestorService-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PackageIngestorPort {


    /**
     * 
     * @param packageIngestorRequest
     * @return
     *     returns com.accenture.ams.pkgingestor.PackageIngestorResponse
     */
    @WebMethod(operationName = "PackageIngestorService", action = "http://ws.be.avs.accenture.com/PackageIngestorService-v1/PackageIngestorRequest")
    @WebResult(name = "PackageIngestorResponse", targetNamespace = "http://accenture.avs.packageingestor.types", partName = "PackageIngestorResponse")
    public PackageIngestorResponse packageIngestorService(
        @WebParam(name = "PackageIngestorRequest", targetNamespace = "http://accenture.avs.packageingestor.types", partName = "PackageIngestorRequest")
        PackageIngestorRequest packageIngestorRequest);

}
