<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:tns="http://ws.be.avs.accenture.com/GetPriceByUserService-v1" 
xmlns:ns="http://ports.accenture.avs.getpricebyuser/GetPriceByUserService-v1" 
targetNamespace="http://ws.be.avs.accenture.com/GetPriceByUserService-v1">
	<wsdl:import namespace="http://ports.accenture.avs.getpricebyuser/GetPriceByUserService-v1" location="AVS_GetPriceByUser_Message.wsdl"/>
	<wsdl:binding name="SoapBinding" type="ns:GetPriceByUserPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetPPVPrice">
			<soap:operation soapAction="http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetPPVPriceRequest" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="GetContentPrice">
			<soap:operation soapAction="http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetContentPriceRequest" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="GetProductPrice">
			<soap:operation soapAction="http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetProductPrice" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="GetBundlePrice">
			<soap:operation soapAction="http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetBundlePriceRequest" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
			
	</wsdl:binding>
	<wsdl:service name="GetPriceByUserService">
		<wsdl:port name="GetPriceByUserServicePort" binding="tns:SoapBinding">
			<soap:address location="http://localhost/GetPriceByUserService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>