
package com.accenture.ams.getpricebyuserservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GetPriceByUserService", targetNamespace = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1", wsdlLocation = "file:/C:/Users/r.mastrodomenico/Documents/EclipseWorkspace_Indigo_EE/AMS/WebContent/wsdl/getPriceByUser/AVS_GetPriceByUser_Service.wsdl")
public class GetPriceByUserService
    extends Service
{

    private final static URL GETPRICEBYUSERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.accenture.ams.getpricebyuserservice.GetPriceByUserService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.accenture.ams.getpricebyuserservice.GetPriceByUserService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/r.mastrodomenico/Documents/EclipseWorkspace_Indigo_EE/AMS/WebContent/wsdl/getPriceByUser/AVS_GetPriceByUser_Service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/r.mastrodomenico/Documents/EclipseWorkspace_Indigo_EE/AMS/WebContent/wsdl/getPriceByUser/AVS_GetPriceByUser_Service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GETPRICEBYUSERSERVICE_WSDL_LOCATION = url;
    }

    public GetPriceByUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetPriceByUserService() {
        super(GETPRICEBYUSERSERVICE_WSDL_LOCATION, new QName("http://ws.be.avs.accenture.com/GetPriceByUserService-v1", "GetPriceByUserService"));
    }

    /**
     * 
     * @return
     *     returns GetPriceByUserPort
     */
    @WebEndpoint(name = "GetPriceByUserServicePort")
    public GetPriceByUserPort getGetPriceByUserServicePort() {
        return super.getPort(new QName("http://ws.be.avs.accenture.com/GetPriceByUserService-v1", "GetPriceByUserServicePort"), GetPriceByUserPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPriceByUserPort
     */
    @WebEndpoint(name = "GetPriceByUserServicePort")
    public GetPriceByUserPort getGetPriceByUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.be.avs.accenture.com/GetPriceByUserService-v1", "GetPriceByUserServicePort"), GetPriceByUserPort.class, features);
    }

}
