
package com.accenture.ams.getpricebyuserservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserRequest;
import wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetPriceByUserPort", targetNamespace = "http://ports.accenture.avs.getpricebyuser/GetPriceByUserService-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	wsclient.commontypes.getpricebyuser.avs.accenture.ObjectFactory.class,
	wsclient.types.getpricebyuser.avs.accenture.ObjectFactory.class
})
public interface GetPriceByUserPort {


    /**
     * 
     * @param getPpvPriceByUserRequest
     * @return
     *     returns types.getpricebyuser.avs.accenture.GetPriceByUserResponse
     */
    @WebMethod(operationName = "GetPPVPrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetPPVPriceRequest")
    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    public GetPriceByUserResponse getPPVPrice(
        @WebParam(name = "GetPpvPriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPpvPriceByUserRequest")
        GetPriceByUserRequest getPpvPriceByUserRequest);

    /**
     * 
     * @param getContentPriceByUserRequest
     * @return
     *     returns types.getpricebyuser.avs.accenture.GetPriceByUserResponse
     */
    @WebMethod(operationName = "GetContentPrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetContentPriceRequest")
    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    public GetPriceByUserResponse getContentPrice(
        @WebParam(name = "GetContentPriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetContentPriceByUserRequest")
        GetPriceByUserRequest getContentPriceByUserRequest);

    /**
     * 
     * @param getProductPriceByUserRequest
     * @return
     *     returns types.getpricebyuser.avs.accenture.GetPriceByUserResponse
     */
    @WebMethod(operationName = "GetProductPrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetProductPrice")
    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    public GetPriceByUserResponse getProductPrice(
        @WebParam(name = "GetProductPriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetProductPriceByUserRequest")
        GetPriceByUserRequest getProductPriceByUserRequest);

    /**
     * 
     * @param getBundlePriceByUserRequest
     * @return
     *     returns types.getpricebyuser.avs.accenture.GetPriceByUserResponse
     */
    @WebMethod(operationName = "GetBundlePrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetBundlePriceRequest")
    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    public GetPriceByUserResponse getBundlePrice(
        @WebParam(name = "GetBundlePriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetBundlePriceByUserRequest")
        GetPriceByUserRequest getBundlePriceByUserRequest);

}
