/**package com.accenture.ams.accountmgmtservice;

//import com.sun.xml.ws.developer.SchemaValidation;
import javax.jws.WebService;
import javax.xml.ws.BindingType;

import org.jboss.ws.annotation.SchemaValidation;
import org.xml.sax.ErrorHandler;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import com.accenture.ams.db.util.LogUtil;

import types.accountmgmt.avs.accenture.AccountMgmtResponse;
import types.accountmgmt.avs.accenture.CrmAccountMgmtRequest;
import types.accountmgmt.avs.accenture.CrmContentPurchaseRequest;
import types.accountmgmt.avs.accenture.SdpAccountProfileDataResponse;
import types.accountmgmt.avs.accenture.SdpDataRequest;
import types.accountmgmt.avs.accenture.SdpPartyProfileDataResponse;
import types.accountmgmt.avs.accenture.UpdateCrmAccountCommercialProfileRequest;
import types.accountmgmt.avs.accenture.UpdateUserPwdRequest;
import types.accountmgmt.avs.accenture.UpdateUserRequest;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.4 Generated
 * source version: 2.1
 * 
 */

/**
@SchemaValidation(enabled = true, schemaLocation = "WEB-INF/wsdl/AccountManagement/AVS_AccountManagement_Types.xsd")
@WebService(portName = "AccountMgmtServicePort", serviceName = "AccountMgmtService", targetNamespace = "http://ws.be.avs.accenture.com/AccountMgmtService-v1", wsdlLocation = "WEB-INF/wsdl/AccountManagement/AVS_AccountManagement_Service.wsdl", endpointInterface = "com.accenture.avs.be.ws.accountmgmtservice_v1.AccountMgmtPort")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class AccountMgmtService_AccountMgmtServicePortImplOS extends
		AccountMgmtService_AccountMgmtServicePortImpl implements ErrorHandler{

	public AccountMgmtService_AccountMgmtServicePortImplOS() {
		super();
		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm wrapper service for all services");
	}

	public AccountMgmtResponse crmAccountMgmtService(
			CrmAccountMgmtRequest crmAccountMgmtRequest) {
		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm in crmAccountMgmtService");
		return super.crmAccountMgmtService(crmAccountMgmtRequest);

	};

	public AccountMgmtResponse updateUserPwdService(
			UpdateUserPwdRequest updateUserPwdRequest) {
		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm in updateUserPwdService");
		return super.updateUserPwdService(updateUserPwdRequest);
	};

	public AccountMgmtResponse updateUserService(
			UpdateUserRequest updateUserRequest) {
		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm in updateUserService");
		return super.updateUserService(updateUserRequest);
	}

	public AccountMgmtResponse updateCrmAccountCommercialProfileService(
			UpdateCrmAccountCommercialProfileRequest updateCrmAccountCommercialProfileRequest) {
		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm in updateCrmAccountCommercialProfileService");
		return super
				.updateCrmAccountCommercialProfileService(updateCrmAccountCommercialProfileRequest);
	}

	public AccountMgmtResponse crmContentPurchaseService(
			CrmContentPurchaseRequest crmContentPurchaseRequest) {
		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm in crmContentPurchaseService");
		return super.crmContentPurchaseService(crmContentPurchaseRequest);
	}
	
	public SdpPartyProfileDataResponse getSdpPartyProfileDataService(
			SdpDataRequest sdpDataRequestParty) {
		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm in getSdpPartyProfileDataService");
		return super.getSdpPartyProfileDataService(sdpDataRequestParty);
	}
	
	public SdpAccountProfileDataResponse getSdpAccountProfileDataService(
			SdpDataRequest sdpDataRequestProfile) {

		LogUtil.writeCommonLog("DEBUG",
				AccountMgmtService_AccountMgmtServicePortImplOS.class,
				"INTERNAL", "I'm in getSdpAccountProfileDataService");
		return super.getSdpAccountProfileDataService(sdpDataRequestProfile);
	}

	public void error(SAXParseException arg0) throws SAXException {
		// TODO Auto-generated method stub
		
	}

	public void fatalError(SAXParseException arg0) throws SAXException {
		// TODO Auto-generated method stub
		
	}

	public void warning(SAXParseException arg0) throws SAXException {
		// TODO Auto-generated method stub
		
	}	
	
//	public void error(SAXParseException ex) throws SAXException {
//		LogUtil.writeErrorLog(
//				AccountMgmtService_AccountMgmtServicePortImplOS.class,
//				"ERROR ", ex);
//		isRequestInError = true;
//		stringException = ex.toString();
//	}
//
//	public void fatalError(SAXParseException ex) throws SAXException {
//		LogUtil.writeErrorLog(
//				AccountMgmtService_AccountMgmtServicePortImplOS.class,
//				"ERROR ", ex);
//		isRequestInError = true;
//		stringException = ex.toString();
//	}
//
//	public void warning(SAXParseException ex) throws SAXException {
//		LogUtil.writeErrorLog(
//				AccountMgmtService_AccountMgmtServicePortImplOS.class,
//				"ERROR ", ex);
//	}
//
//	@Override
//	protected String checkRequest() {
//		String returnStr = null;
//		if (isRequestInError) {
//			LogUtil.writeCommonLog("ERROR",
//					AccountMgmtService_AccountMgmtServicePortImplOS.class,
//					"INTERNAL", "Request is in error !!!!");
//			StringBuffer desc = new StringBuffer(
//					AccountMgmtServiceConstant.RET_DESC[AccountMgmtServiceConstant.RET_GENERIC_ERROR]);
//			desc.append("|" + stringException);
//			returnStr = desc.toString();
//		}
//		isRequestInError = false;
//		stringException = "";
//		return returnStr;
//	}	
} */