package wsclient.packageingestor.avs.accenture.ports.packageingestorservice_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.9-redhat-2
 * 2013-05-07T10:09:19.835+02:00
 * Generated source version: 2.4.9-redhat-2
 * 
 */
@WebService(targetNamespace = "http://ports.accenture.avs.packageingestor/PackageIngestorService-v1", name = "PackageIngestorPort")
@XmlSeeAlso({wsclient.types.packageingestor.avs.accenture.ObjectFactory.class, wsclient.commontypes.packageingestor.avs.accenture.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PackageIngestorPort {

    @WebResult(name = "PackageIngestorResponse", targetNamespace = "http://accenture.avs.packageingestor.types", partName = "PackageIngestorResponse")
    @WebMethod(operationName = "PackageIngestorService", action = "http://ws.be.avs.accenture.com/PackageIngestorService-v1/PackageIngestorRequest")
    public wsclient.types.packageingestor.avs.accenture.PackageIngestorResponse packageIngestorService(
        @WebParam(partName = "PackageIngestorRequest", name = "PackageIngestorRequest", targetNamespace = "http://accenture.avs.packageingestor.types")
        wsclient.types.packageingestor.avs.accenture.PackageIngestorRequest packageIngestorRequest
    );
}
