//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 03:03:47 PM CET 
//

package com.accenture.sdp.csmfe.webservices.request.device;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for maximumAllowedDevicesType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="maximumAllowedDevicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="device" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="deviceChannel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="maximumNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "maximumAllowedDevicesType", propOrder = { "device" })
public class MaximumAllowedDevicesType {

	private List<MaximumAllowedDevicesType.Device> device;

	/**
	 * Gets the value of the device property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the device property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDevice().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link MaximumAllowedDevicesType.Device }
	 * 
	 * 
	 */
	public List<MaximumAllowedDevicesType.Device> getDevice() {
		if (device == null) {
			device = new ArrayList<MaximumAllowedDevicesType.Device>();
		}
		return this.device;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="deviceChannel" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="maximumNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "deviceChannel", "maximumNumber" })
	public static class Device {

		@XmlElement(required = true)
		private String deviceChannel;
		@XmlElement(required = true)
		private Long maximumNumber;

		/**
		 * Gets the value of the deviceChannel property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDeviceChannel() {
			return deviceChannel;
		}

		/**
		 * Sets the value of the deviceChannel property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDeviceChannel(String value) {
			this.deviceChannel = value;
		}

		/**
		 * Gets the value of the maximumNumber property.
		 * 
		 */
		public Long getMaximumNumber() {
			return maximumNumber;
		}

		/**
		 * Sets the value of the maximumNumber property.
		 * 
		 */
		public void setMaximumNumber(Long value) {
			this.maximumNumber = value;
		}

	}

}
