//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 03:03:47 PM CET 
//

package com.accenture.sdp.csmfe.webservices.request.device;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SetPartyDevicePolicyRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetPartyDevicePolicyRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="policies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="policy" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="policyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetPartyDevicePolicyRequest", propOrder = { "policies" })
public class SetPartyDevicePolicyRequest {

	@XmlElement(required = true)
	private SetPartyDevicePolicyRequest.Policies policies;

	/**
	 * Gets the value of the policies property.
	 * 
	 * @return possible object is {@link SetPartyDevicePolicyRequest.Policies }
	 * 
	 */
	public SetPartyDevicePolicyRequest.Policies getPolicies() {
		return policies;
	}

	/**
	 * Sets the value of the policies property.
	 * 
	 * @param value
	 *            allowed object is {@link SetPartyDevicePolicyRequest.Policies }
	 * 
	 */
	public void setPolicies(SetPartyDevicePolicyRequest.Policies value) {
		this.policies = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="policy" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *                   &lt;element name="policyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "policy" })
	public static class Policies {

		private List<SetPartyDevicePolicyRequest.Policies.Policy> policy;

		/**
		 * Gets the value of the policy property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the policy property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPolicy().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link SetPartyDevicePolicyRequest.Policies.Policy }
		 * 
		 * 
		 */
		public List<SetPartyDevicePolicyRequest.Policies.Policy> getPolicy() {
			if (policy == null) {
				policy = new ArrayList<SetPartyDevicePolicyRequest.Policies.Policy>();
			}
			return this.policy;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
		 *         &lt;element name="policyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "partyId", "policyId" })
		public static class Policy {

			@XmlElement(required = true)
			private Long partyId;
			@XmlElement(required = true)
			private Long policyId;

			/**
			 * Gets the value of the partyId property.
			 * 
			 */
			public Long getPartyId() {
				return partyId;
			}

			/**
			 * Sets the value of the partyId property.
			 * 
			 */
			public void setPartyId(Long value) {
				this.partyId = value;
			}

			/**
			 * Gets the value of the policyId property.
			 * 
			 */
			public Long getPolicyId() {
				return policyId;
			}

			/**
			 * Sets the value of the policyId property.
			 * 
			 */
			public void setPolicyId(Long value) {
				this.policyId = value;
			}

		}

	}

}
