package wsclient.getpricebyuser.avs.accenture.ports.getpricebyuserservice_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.9-redhat-2
 * 2013-05-07T10:07:00.156+02:00
 * Generated source version: 2.4.9-redhat-2
 * 
 */
@WebService(targetNamespace = "http://ports.accenture.avs.getpricebyuser/GetPriceByUserService-v1", name = "GetPriceByUserPort")
@XmlSeeAlso({wsclient.types.getpricebyuser.avs.accenture.ObjectFactory.class, wsclient.commontypes.getpricebyuser.avs.accenture.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetPriceByUserPort {

    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    @WebMethod(operationName = "GetProductPrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetProductPrice")
    public wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserResponse getProductPrice(
        @WebParam(partName = "GetProductPriceByUserRequest", name = "GetProductPriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types")
        wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserRequest getProductPriceByUserRequest
    );

    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    @WebMethod(operationName = "GetPPVPrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetPPVPriceRequest")
    public wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserResponse getPPVPrice(
        @WebParam(partName = "GetPpvPriceByUserRequest", name = "GetPpvPriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types")
        wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserRequest getPpvPriceByUserRequest
    );

    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    @WebMethod(operationName = "GetBundlePrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetBundlePriceRequest")
    public wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserResponse getBundlePrice(
        @WebParam(partName = "GetBundlePriceByUserRequest", name = "GetBundlePriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types")
        wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserRequest getBundlePriceByUserRequest
    );

    @WebResult(name = "GetPriceByUserResponse", targetNamespace = "http://accenture.avs.getpricebyuser.types", partName = "GetPriceByUserResponse")
    @WebMethod(operationName = "GetContentPrice", action = "http://ws.be.avs.accenture.com/GetPriceByUserService-v1/GetContentPriceRequest")
    public wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserResponse getContentPrice(
        @WebParam(partName = "GetContentPriceByUserRequest", name = "GetContentPriceByUserRequest", targetNamespace = "http://accenture.avs.getpricebyuser.types")
        wsclient.types.getpricebyuser.avs.accenture.GetPriceByUserRequest getContentPriceByUserRequest
    );
}
