//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 03:52:17 PM CEST 
//


package com.accenture.sdp.csmfe.restservices.request.shoppingcart;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.accenture.sdp.csmfe.restservices.requests.shoppingcart package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RemoveItemsFromShoppingCartRequest_QNAME = new QName("", "RemoveItemsFromShoppingCartRequest");
    private final static QName _ShoppingCartChangeStatusRequest_QNAME = new QName("", "ShoppingCartChangeStatusRequest");
    private final static QName _AddItemsToShoppingCartRequest_QNAME = new QName("", "AddItemsToShoppingCartRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.accenture.sdp.csmfe.restservices.requests.shoppingcart
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShoppingCartType }
     * 
     */
    public ShoppingCartType createShoppingCartType() {
        return new ShoppingCartType();
    }

    /**
     * Create an instance of {@link AddItemsToShoppingCartRequest }
     * 
     */
    public AddItemsToShoppingCartRequest createAddItemsToShoppingCartRequest() {
        return new AddItemsToShoppingCartRequest();
    }

    /**
     * Create an instance of {@link RemoveItemsFromShoppingCartRequest }
     * 
     */
    public RemoveItemsFromShoppingCartRequest createRemoveItemsFromShoppingCartRequest() {
        return new RemoveItemsFromShoppingCartRequest();
    }

    /**
     * Create an instance of {@link ShoppingCartChangeStatusRequest }
     * 
     */
    public ShoppingCartChangeStatusRequest createShoppingCartChangeStatusRequest() {
        return new ShoppingCartChangeStatusRequest();
    }

    /**
     * Create an instance of {@link RemoveShoppingCartItemType }
     * 
     */
    public RemoveShoppingCartItemType createRemoveShoppingCartItemType() {
        return new RemoveShoppingCartItemType();
    }

    /**
     * Create an instance of {@link ShoppingCartItemExtendedType }
     * 
     */
    public ShoppingCartItemExtendedType createShoppingCartItemExtendedType() {
        return new ShoppingCartItemExtendedType();
    }

    /**
     * Create an instance of {@link ShoppingCartItemBaseType }
     * 
     */
    public ShoppingCartItemBaseType createShoppingCartItemBaseType() {
        return new ShoppingCartItemBaseType();
    }

    /**
     * Create an instance of {@link ShoppingCartType.Items }
     * 
     */
    public ShoppingCartType.Items createShoppingCartTypeItems() {
        return new ShoppingCartType.Items();
    }

    /**
     * Create an instance of {@link AddItemsToShoppingCartRequest.Items }
     * 
     */
    public AddItemsToShoppingCartRequest.Items createAddItemsToShoppingCartRequestItems() {
        return new AddItemsToShoppingCartRequest.Items();
    }

    /**
     * Create an instance of {@link RemoveItemsFromShoppingCartRequest.Items }
     * 
     */
    public RemoveItemsFromShoppingCartRequest.Items createRemoveItemsFromShoppingCartRequestItems() {
        return new RemoveItemsFromShoppingCartRequest.Items();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveItemsFromShoppingCartRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RemoveItemsFromShoppingCartRequest")
    public JAXBElement<RemoveItemsFromShoppingCartRequest> createRemoveItemsFromShoppingCartRequest(RemoveItemsFromShoppingCartRequest value) {
        return new JAXBElement<RemoveItemsFromShoppingCartRequest>(_RemoveItemsFromShoppingCartRequest_QNAME, RemoveItemsFromShoppingCartRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShoppingCartChangeStatusRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShoppingCartChangeStatusRequest")
    public JAXBElement<ShoppingCartChangeStatusRequest> createShoppingCartChangeStatusRequest(ShoppingCartChangeStatusRequest value) {
        return new JAXBElement<ShoppingCartChangeStatusRequest>(_ShoppingCartChangeStatusRequest_QNAME, ShoppingCartChangeStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddItemsToShoppingCartRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddItemsToShoppingCartRequest")
    public JAXBElement<AddItemsToShoppingCartRequest> createAddItemsToShoppingCartRequest(AddItemsToShoppingCartRequest value) {
        return new JAXBElement<AddItemsToShoppingCartRequest>(_AddItemsToShoppingCartRequest_QNAME, AddItemsToShoppingCartRequest.class, null, value);
    }

}
