//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 03:52:17 PM CEST 
//


package com.accenture.sdp.csmfe.restservices.request.shoppingcart;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shoppingCartItemExtendedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shoppingCartItemExtendedType">
 *   &lt;complexContent>
 *     &lt;extension base="{}shoppingCartItemBaseType">
 *       &lt;sequence>
 *         &lt;element name="subTotalPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shoppingCartItemExtendedType", propOrder = {
    "subTotalPrice"
})
public class ShoppingCartItemExtendedType
    extends ShoppingCartItemBaseType
{

    protected BigDecimal subTotalPrice;

    /**
     * Gets the value of the subTotalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubTotalPrice() {
        return subTotalPrice;
    }

    /**
     * Sets the value of the subTotalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubTotalPrice(BigDecimal value) {
        this.subTotalPrice = value;
    }

}
