USE CSMDB_TENANTX;

/* VIEW CREATION */
CREATE VIEW `SDP_SOLUTION_OFFER_EXTERNAL_ID_VIEW` AS SELECT * FROM `SDP_SOLUTION_OFFER_EXTERNAL_ID`;

CREATE OR REPLACE VIEW `SDP_SOLUTION_OFFER_VIEW` AS
	select `SO`.`SOLUTION_OFFER_ID` AS `SOLUTION_OFFER_ID`,
	`SO`.`PARENT_SOLUTION_OFFER_ID` AS `PARENT_SOLUTION_OFFER_ID`,
	`SO`.`SOLUTION_ID` AS `SOLUTION_ID`,
	`SO`.`SOLUTION_OFFER_NAME` AS `SOLUTION_OFFER_NAME`,
    `SO`.`SOLUTION_OFFER_DESCRIPTION` AS `SOLUTION_OFFER_DESCRIPTION`,
	`SO`.`STATUS_ID` AS `STATUS_ID`,
	`SO`.`SOLUTION_OFFER_PROFILE` AS `SOLUTION_OFFER_PROFILE`,
	NULL AS `EXTERNAL_ID`,
	`SO`.`START_DATE` AS `START_DATE`,
	`SO`.`END_DATE` AS `END_DATE`,
	`SO`.`CREATED_BY_ID` AS `CREATED_BY_ID`,
    `SO`.`CREATED_DATE` AS `CREATED_DATE`,
	`SO`.`UPDATED_BY_ID` AS `UPDATED_BY_ID`,
	`SO`.`UPDATED_DATE` AS `UPDATED_DATE`,
	`SO`.`DELETED_BY_ID` AS `DELETED_BY_ID`,
	`SO`.`DELETED_DATE` AS `DELETED_DATE`,
	`SO`.`CHG_STATUS_BY_ID` AS `CHG_STATUS_BY_ID`,
	`SO`.`CHG_STATUS_DATE` AS `CHG_STATUS_DATE`,
	`SO`.`IS_BASIC_PROFILE` AS `IS_BASIC_PROFILE`,
	`SO`.`DURATION` AS `DURATION`,
    `SO`.`SOLUTION_OFFER_TYPE` AS `SOLUTION_OFFER_TYPE`
    from `SDP_SOLUTION_OFFER` `SO`;

/*
CREATE OR REPLACE  VIEW `sdp_voucher_view` AS
    select 
        v.`VOUCHER_ID` AS `VOUCHER_ID`,
        v.`VOUCHER_CODE` AS `VOUCHER_CODE`,
        vc.`VOUCHER_TYPE` AS `VOUCHER_TYPE`,
        vc.`VALIDITY_PERIOD` AS `VALIDITY_PERIOD`,
		vc.`START_DATE` AS `START_DATE`,
		vc.`END_DATE` AS `END_DATE`,
        vc.`SOLUTION_OFFER_ID` AS `SOLUTION_OFFER_ID`,
        v.`PARTY_ID` AS `PARTY_ID`,
        v.`CREATED_BY_ID` AS `CREATED_BY_ID`,
        v.`CREATED_DATE` AS `CREATED_DATE`,
        v.`UPDATED_BY_ID` AS `UPDATED_BY_ID`,
        v.`UPDATED_DATE` AS `UPDATED_DATE`
    from
        `sdp_voucher` v join SDP_VOUCHER_CAMPAIGN vc on v.VOUCHER_TYPE = vc.VOUCHER_TYPE;
*/

CREATE OR REPLACE  VIEW `sdp_voucher_view` AS select * from `sdp_voucher` v;
CREATE OR REPLACE  VIEW `sdp_voucher_campaign_view` AS select * from `sdp_voucher_campaign` vc;