
CREATE DATABASE METERING_TENANTX;

ALTER SCHEMA METERING_TENANT1 DEFAULT CHARACTER

SET utf8 DEFAULT COLLATE utf8_general_ci;

USE METERING_TENANTX;

/*--------------------------------------------------------
--  DDL for Table REF_CSM_CONSTANTS
--------------------------------------------------------*/


CREATE TABLE `REF_EVENT_TYPE` (
	`EVENT_TYPE_ID` BIGINT NOT NULL COMMENT 'event type id',
	`EVENT_TYPE_NAME` VARCHAR(50) NOT NULL COMMENT 'event type name',
	PRIMARY KEY (`EVENT_TYPE_ID`)
) ENGINE=INNODB COMMENT 'ref table for trace device event type';


CREATE TABLE `SDP_DEVICE_TRACING` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'device trace identifier',
	`DEVICE_UUID` VARCHAR(128) DEFAULT NULL COMMENT 'device unique identifier', 
	`PARTY_ID` BIGINT DEFAULT NULL COMMENT 'party identifier',
	`EVENT_TYPE_ID` BIGINT NOT NULL  COMMENT 'event type id',
	`EVENT_TIMESTAMP` DATETIME NOT NULL COMMENT 'event timestamp',
	`RESULT` VARCHAR(3) NOT NULL COMMENT 'result code', 
	`RESULT_DESCRIPTION` VARCHAR(255) NOT NULL COMMENT 'result description', 
	PRIMARY KEY (`ID`),
	INDEX (`DEVICE_UUID`),
	INDEX (`PARTY_ID`),
	CONSTRAINT `FK-DEVICE_TRACING-EVENT_TYPE` FOREIGN KEY (`EVENT_TYPE_ID`) REFERENCES `REF_EVENT_TYPE`(`EVENT_TYPE_ID`)
	
) ENGINE=INNODB COMMENT 'table for trace device activities';


INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('1', 'DEVICE_REGISTRATION');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('2', 'DEVICE_UNREGISTRATION');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('3', 'AUTHENTICATE_DEVICE');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('4', 'RESET_SAFETY_PERIOD');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('5', 'RESET_DEVICE_ASSOCIATIONS');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('6', 'ADD_TO_BL');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('7', 'DEL_FROM_BL');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('8', 'ADD_TO_WL');
INSERT INTO `ref_event_type` (`EVENT_TYPE_ID`, `EVENT_TYPE_NAME`) VALUES ('9', 'DEL_FROM_WL');


