package wsclient.accountmgmt.avs.accenture.ports.accountmgmtservice_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.9-redhat-2
 * 2013-05-03T17:07:55.527+02:00
 * Generated source version: 2.4.9-redhat-2
 * 
 */
@WebService(targetNamespace = "http://ports.accenture.avs.accountmgmt/AccountMgmtService-v1", name = "AccountMgmtPort")
@XmlSeeAlso({wsclient.commontypes.accountmgmt.avs.accenture.ObjectFactory.class, wsclient.types.accountmgmt.avs.accenture.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccountMgmtPort {

    @WebResult(name = "AccountMgmtResponse", targetNamespace = "http://accenture.avs.accountmgmt.types", partName = "AccountMgmtResponse")
    @WebMethod(operationName = "UpdateUserService", action = "http://ws.be.avs.accenture.com/AccountMgmtService-v1/UpdateUserRequest")
    public wsclient.types.accountmgmt.avs.accenture.AccountMgmtResponse updateUserService(
        @WebParam(partName = "UpdateUserRequest", name = "UpdateUserRequest", targetNamespace = "http://accenture.avs.accountmgmt.types")
        wsclient.types.accountmgmt.avs.accenture.UpdateUserRequest updateUserRequest
    );

    @WebResult(name = "AccountMgmtResponse", targetNamespace = "http://accenture.avs.accountmgmt.types", partName = "AccountMgmtResponse")
    @WebMethod(operationName = "UpdateUserPwdService", action = "http://ws.be.avs.accenture.com/AccountMgmtService-v1/UpdateUserPwdRequest")
    public wsclient.types.accountmgmt.avs.accenture.AccountMgmtResponse updateUserPwdService(
        @WebParam(partName = "UpdateUserPwdRequest", name = "UpdateUserPwdRequest", targetNamespace = "http://accenture.avs.accountmgmt.types")
        wsclient.types.accountmgmt.avs.accenture.UpdateUserPwdRequest updateUserPwdRequest
    );

    @WebResult(name = "AccountMgmtResponse", targetNamespace = "http://accenture.avs.accountmgmt.types", partName = "AccountMgmtResponse")
    @WebMethod(operationName = "UpdateCrmAccountCommercialProfileService", action = "http://ws.be.avs.accenture.com/AccountMgmtService-v1/UpdateCrmAccountCommercialProfileRequest")
    public wsclient.types.accountmgmt.avs.accenture.AccountMgmtResponse updateCrmAccountCommercialProfileService(
        @WebParam(partName = "UpdateCrmAccountCommercialProfileRequest", name = "UpdateCrmAccountCommercialProfileRequest", targetNamespace = "http://accenture.avs.accountmgmt.types")
        wsclient.types.accountmgmt.avs.accenture.UpdateCrmAccountCommercialProfileRequest updateCrmAccountCommercialProfileRequest
    );

    @WebResult(name = "GetSdpAccountProfileDataResponse", targetNamespace = "http://accenture.avs.accountmgmt.types", partName = "GetSdpAccountProfileDataResponse")
    @WebMethod(operationName = "GetSdpAccountProfileDataService", action = "http://ws.be.avs.accenture.com/AccountMgmtService-v1/SdpDataRequestProfile")
    public wsclient.types.accountmgmt.avs.accenture.SdpAccountProfileDataResponse getSdpAccountProfileDataService(
        @WebParam(partName = "SdpDataRequestProfile", name = "SdpDataRequestProfile", targetNamespace = "http://accenture.avs.accountmgmt.types")
        wsclient.types.accountmgmt.avs.accenture.SdpDataRequest sdpDataRequestProfile
    );

    @WebResult(name = "AccountMgmtResponse", targetNamespace = "http://accenture.avs.accountmgmt.types", partName = "AccountMgmtResponse")
    @WebMethod(operationName = "CrmContentPurchaseService", action = "http://ws.be.avs.accenture.com/AccountMgmtService-v1/CrmContentPurchaseRequest")
    public wsclient.types.accountmgmt.avs.accenture.AccountMgmtResponse crmContentPurchaseService(
        @WebParam(partName = "CrmContentPurchaseRequest", name = "CrmContentPurchaseRequest", targetNamespace = "http://accenture.avs.accountmgmt.types")
        wsclient.types.accountmgmt.avs.accenture.CrmContentPurchaseRequest crmContentPurchaseRequest
    );

    @WebResult(name = "GetSdpPartyProfileDataResponse", targetNamespace = "http://accenture.avs.accountmgmt.types", partName = "GetSdpPartyProfileDataResponse")
    @WebMethod(operationName = "GetSdpPartyProfileDataService", action = "http://ws.be.avs.accenture.com/AccountMgmtService-v1/SdpDataRequestParty")
    public wsclient.types.accountmgmt.avs.accenture.SdpPartyProfileDataResponse getSdpPartyProfileDataService(
        @WebParam(partName = "SdpDataRequestParty", name = "SdpDataRequestParty", targetNamespace = "http://accenture.avs.accountmgmt.types")
        wsclient.types.accountmgmt.avs.accenture.SdpDataRequest sdpDataRequestParty
    );

    @WebResult(name = "AccountMgmtResponse", targetNamespace = "http://accenture.avs.accountmgmt.types", partName = "AccountMgmtResponse")
    @WebMethod(operationName = "CrmAccountMgmtService", action = "http://ws.be.avs.accenture.com/AccountMgmtService-v1/CrmAccountMgmtRequest")
    public wsclient.types.accountmgmt.avs.accenture.AccountMgmtResponse crmAccountMgmtService(
        @WebParam(partName = "CrmAccountMgmtRequest", name = "CrmAccountMgmtRequest", targetNamespace = "http://accenture.avs.accountmgmt.types")
        wsclient.types.accountmgmt.avs.accenture.CrmAccountMgmtRequest crmAccountMgmtRequest
    );
}
