//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.19 at 02:45:36 PM CET 
//

package com.accenture.sdp.csmfe.webservices.response.device;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.accenture.sdp.csmfe.webservices.response.BaseInfoResp;

/**
 * <p>
 * Java class for deviceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deviceType">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseInfoResp">
 *       &lt;sequence>
 *         &lt;element name="deviceUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deviceUUIDType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deviceChannel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deviceBrand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deviceModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deviceAlias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isPaired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="lastFruitionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="isBlacklisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="isWhitelisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="blacklistReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deviceType", propOrder = { "deviceUUID", "deviceUUIDType", "deviceChannel", "deviceBrand", "deviceModel", "deviceAlias", "status", "isPaired",
		"lastFruitionDate", "isBlacklisted", "isWhitelisted", "blacklistReason", "partyId" })
public class DeviceType extends BaseInfoResp {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7377002629985474379L;

	@XmlElement(required = true)
	private String deviceUUID;
	@XmlElement(required = true)
	private String deviceUUIDType;
	@XmlElement(required = true)
	private String deviceChannel;
	private String deviceBrand;
	private String deviceModel;
	private String deviceAlias;
	@XmlElement(required = true)
	private String status;
	private boolean isPaired;
	private Date lastFruitionDate;
	private boolean isBlacklisted;
	private boolean isWhitelisted;
	private String blacklistReason;
	@XmlElement(required = true)
	private Long partyId;

	/**
	 * Gets the value of the deviceUUID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceUUID() {
		return deviceUUID;
	}

	/**
	 * Sets the value of the deviceUUID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceUUID(String value) {
		this.deviceUUID = value;
	}

	/**
	 * Gets the value of the deviceUUIDType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceUUIDType() {
		return deviceUUIDType;
	}

	/**
	 * Sets the value of the deviceUUIDType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceUUIDType(String value) {
		this.deviceUUIDType = value;
	}

	/**
	 * Gets the value of the deviceChannel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceChannel() {
		return deviceChannel;
	}

	/**
	 * Sets the value of the deviceChannel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceChannel(String value) {
		this.deviceChannel = value;
	}

	/**
	 * Gets the value of the deviceBrand property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceBrand() {
		return deviceBrand;
	}

	/**
	 * Sets the value of the deviceBrand property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceBrand(String value) {
		this.deviceBrand = value;
	}

	/**
	 * Gets the value of the deviceModel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceModel() {
		return deviceModel;
	}

	/**
	 * Sets the value of the deviceModel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceModel(String value) {
		this.deviceModel = value;
	}

	/**
	 * Gets the value of the deviceAlias property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceAlias() {
		return deviceAlias;
	}

	/**
	 * Sets the value of the deviceAlias property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceAlias(String value) {
		this.deviceAlias = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the isPaired property.
	 * 
	 */
	public boolean isIsPaired() {
		return isPaired;
	}

	/**
	 * Sets the value of the isPaired property.
	 * 
	 */
	public void setIsPaired(boolean value) {
		this.isPaired = value;
	}

	/**
	 * Gets the value of the lastFruitionDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getLastFruitionDate() {
		return lastFruitionDate;
	}

	/**
	 * Sets the value of the lastFruitionDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setLastFruitionDate(Date value) {
		this.lastFruitionDate = value;
	}

	/**
	 * Gets the value of the isBlacklisted property.
	 * 
	 */
	public boolean isIsBlacklisted() {
		return isBlacklisted;
	}

	/**
	 * Sets the value of the isBlacklisted property.
	 * 
	 */
	public void setIsBlacklisted(boolean value) {
		this.isBlacklisted = value;
	}

	/**
	 * Gets the value of the isWhitelisted property.
	 * 
	 */
	public boolean isIsWhitelisted() {
		return isWhitelisted;
	}

	/**
	 * Sets the value of the isWhitelisted property.
	 * 
	 */
	public void setIsWhitelisted(boolean value) {
		this.isWhitelisted = value;
	}

	/**
	 * Gets the value of the blacklistReason property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBlacklistReason() {
		return blacklistReason;
	}

	/**
	 * Sets the value of the blacklistReason property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBlacklistReason(String value) {
		this.blacklistReason = value;
	}

	/**
	 * Gets the value of the partyId property.
	 * 
	 */
	public Long getPartyId() {
		return partyId;
	}

	/**
	 * Sets the value of the partyId property.
	 * 
	 */
	public void setPartyId(Long partyId) {
		this.partyId = partyId;
	}

}
