//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 03:03:47 PM CET 
//

package com.accenture.sdp.csmfe.webservices.response.device;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for policyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="policyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="policyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="policyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maxAssociationsNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="safetyPeriodDuration" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="isDefaultPolicy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maximumAllowedDevices">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="device" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="deviceChannel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="maximumNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "policyType", propOrder = { "policyId", "policyName", "maxAssociationsNumber", "safetyPeriodDuration", "isDefaultPolicy",
		"maximumAllowedDevices" })
public class PolicyType {

	@XmlElement(required = true)
	private Long policyId;
	@XmlElement(required = true)
	private String policyName;
	@XmlElement(required = true)
	private Long maxAssociationsNumber;
	@XmlElement(required = true)
	private Long safetyPeriodDuration;
	private boolean isDefaultPolicy;
	@XmlElement(required = true)
	private PolicyType.MaximumAllowedDevices maximumAllowedDevices;

	/**
	 * Gets the value of the policyId property.
	 * 
	 */
	public Long getPolicyId() {
		return policyId;
	}

	/**
	 * Sets the value of the policyId property.
	 * 
	 */
	public void setPolicyId(Long value) {
		this.policyId = value;
	}

	/**
	 * Gets the value of the policyName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPolicyName() {
		return policyName;
	}

	/**
	 * Sets the value of the policyName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPolicyName(String value) {
		this.policyName = value;
	}

	/**
	 * Gets the value of the maxAssociationsNumber property.
	 * 
	 */
	public Long getMaxAssociationsNumber() {
		return maxAssociationsNumber;
	}

	/**
	 * Sets the value of the maxAssociationsNumber property.
	 * 
	 */
	public void setMaxAssociationsNumber(Long value) {
		this.maxAssociationsNumber = value;
	}

	/**
	 * Gets the value of the safetyPeriodDuration property.
	 * 
	 */
	public Long getSafetyPeriodDuration() {
		return safetyPeriodDuration;
	}

	/**
	 * Sets the value of the safetyPeriodDuration property.
	 * 
	 */
	public void setSafetyPeriodDuration(Long value) {
		this.safetyPeriodDuration = value;
	}

	/**
	 * Gets the value of the isDefaultPolicy property.
	 * 
	 */
	public boolean isIsDefaultPolicy() {
		return isDefaultPolicy;
	}

	/**
	 * Sets the value of the isDefaultPolicy property.
	 * 
	 */
	public void setIsDefaultPolicy(boolean value) {
		this.isDefaultPolicy = value;
	}

	/**
	 * Gets the value of the maximumAllowedDevices property.
	 * 
	 * @return possible object is {@link PolicyType.MaximumAllowedDevices }
	 * 
	 */
	public PolicyType.MaximumAllowedDevices getMaximumAllowedDevices() {
		return maximumAllowedDevices;
	}

	/**
	 * Sets the value of the maximumAllowedDevices property.
	 * 
	 * @param value
	 *            allowed object is {@link PolicyType.MaximumAllowedDevices }
	 * 
	 */
	public void setMaximumAllowedDevices(PolicyType.MaximumAllowedDevices value) {
		this.maximumAllowedDevices = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="device" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="deviceChannel" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="maximumNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "device" })
	public static class MaximumAllowedDevices {

		private List<PolicyType.MaximumAllowedDevices.Device> device;

		/**
		 * Gets the value of the device property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the device property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDevice().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link PolicyType.MaximumAllowedDevices.Device }
		 * 
		 * 
		 */
		public List<PolicyType.MaximumAllowedDevices.Device> getDevice() {
			if (device == null) {
				device = new ArrayList<PolicyType.MaximumAllowedDevices.Device>();
			}
			return this.device;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="deviceChannel" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="maximumNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "deviceChannel", "maximumNumber" })
		public static class Device {

			@XmlElement(required = true)
			private String deviceChannel;
			@XmlElement(required = true)
			private Long maximumNumber;

			/**
			 * Gets the value of the deviceChannel property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDeviceChannel() {
				return deviceChannel;
			}

			/**
			 * Sets the value of the deviceChannel property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDeviceChannel(String value) {
				this.deviceChannel = value;
			}

			/**
			 * Gets the value of the maximumNumber property.
			 * 
			 */
			public Long getMaximumNumber() {
				return maximumNumber;
			}

			/**
			 * Sets the value of the maximumNumber property.
			 * 
			 */
			public void setMaximumNumber(Long value) {
				this.maximumNumber = value;
			}

		}

	}

}
