//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:09:44 PM CET 
//

package com.accenture.sdp.csmfe.webservices.response.device;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.accenture.sdp.csmfe.webservices.response.BaseResp;

/**
 * <p>
 * Java class for SearchAllDeviceBrandsResp complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchAllDeviceBrandsResp">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseResp">
 *       &lt;sequence>
 *         &lt;element name="brands">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="brand">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="brandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="brandName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="isBlacklisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="isWhitelisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="blacklistReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchAllDeviceBrandsResp", propOrder = { "brands" })
public class SearchAllDeviceBrandsResp extends BaseResp {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7794805871375903911L;

	@XmlElement(required = true)
	private SearchAllDeviceBrandsResp.Brands brands;

	/**
	 * Gets the value of the brands property.
	 * 
	 * @return possible object is {@link SearchAllDeviceBrandsResp.Brands }
	 * 
	 */
	public SearchAllDeviceBrandsResp.Brands getBrands() {
		return brands;
	}

	/**
	 * Sets the value of the brands property.
	 * 
	 * @param value
	 *            allowed object is {@link SearchAllDeviceBrandsResp.Brands }
	 * 
	 */
	public void setBrands(SearchAllDeviceBrandsResp.Brands value) {
		this.brands = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
	 *         &lt;element name="brand">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="brandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *                   &lt;element name="brandName" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="isBlacklisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
	 *                   &lt;element name="isWhitelisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
	 *                   &lt;element name="blacklistReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "brand" })
	public static class Brands {

		private List<SearchAllDeviceBrandsResp.Brands.Brand> brand;

		/**
		 * Gets the value of the brand property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the brand property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getBrand().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link SearchAllDeviceBrandsResp.Brands.Brand }
		 * 
		 * 
		 */
		public List<SearchAllDeviceBrandsResp.Brands.Brand> getBrand() {
			if (brand == null) {
				brand = new ArrayList<SearchAllDeviceBrandsResp.Brands.Brand>();
			}
			return this.brand;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="brandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
		 *         &lt;element name="brandName" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="isBlacklisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
		 *         &lt;element name="isWhitelisted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
		 *         &lt;element name="blacklistReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "brandId", "brandName", "isBlacklisted", "isWhitelisted", "blacklistReason" })
		public static class Brand {

			@XmlElement(required = true)
			private Long brandId;
			@XmlElement(required = true)
			private String brandName;
			private boolean isBlacklisted;
			private boolean isWhitelisted;
			private String blacklistReason;

			/**
			 * Gets the value of the brandId property.
			 * 
			 */
			public Long getBrandId() {
				return brandId;
			}

			/**
			 * Sets the value of the brandId property.
			 * 
			 */
			public void setBrandId(Long value) {
				this.brandId = value;
			}

			/**
			 * Gets the value of the brandName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getBrandName() {
				return brandName;
			}

			/**
			 * Sets the value of the brandName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setBrandName(String value) {
				this.brandName = value;
			}

			/**
			 * Gets the value of the isBlacklisted property.
			 * 
			 */
			public boolean isIsBlacklisted() {
				return isBlacklisted;
			}

			/**
			 * Sets the value of the isBlacklisted property.
			 * 
			 */
			public void setIsBlacklisted(boolean value) {
				this.isBlacklisted = value;
			}

			/**
			 * Gets the value of the isWhitelisted property.
			 * 
			 */
			public boolean isIsWhitelisted() {
				return isWhitelisted;
			}

			/**
			 * Sets the value of the isWhitelisted property.
			 * 
			 */
			public void setIsWhitelisted(boolean value) {
				this.isWhitelisted = value;
			}

			/**
			 * Gets the value of the blacklistReason property.
			 * 
			 */
			public String getBlacklistReason() {
				return blacklistReason;
			}

			/**
			 * Sets the value of the blacklistReason property.
			 * 
			 */
			public void setBlacklistReason(String value) {
				this.blacklistReason = value;
			}
		}

	}

}
