//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.18 at 04:02:19 PM CET 
//

package com.accenture.sdp.csmfe.webservices.response.device;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.accenture.sdp.csmfe.webservices.response.BaseResp;

/**
 * <p>
 * Java class for SearchDeviceCountersByPartyIdResp complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchDeviceCountersByPartyIdResp">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseResp">
 *       &lt;sequence>
 *         &lt;element name="registrationsDone" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="safetyPeriodExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="deviceCounters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="deviceCounter" type="{}deviceCounterType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://com.accenture.sdp.csm.webservices.types")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchDeviceCountersByPartyIdResp", propOrder = { "registrationsDone", "safetyPeriodExpirationDate", "deviceCounters" })
public class SearchDeviceCountersByPartyIdResp extends BaseResp {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5108733455422968485L;

	@XmlElement(required = true)
	private Long registrationsDone;
	private Date safetyPeriodExpirationDate;
	@XmlElement(required = true)
	private SearchDeviceCountersByPartyIdResp.DeviceCounters deviceCounters;

	/**
	 * Gets the value of the registrationsDone property.
	 * 
	 */
	public Long getRegistrationsDone() {
		return registrationsDone;
	}

	/**
	 * Sets the value of the registrationsDone property.
	 * 
	 */
	public void setRegistrationsDone(Long value) {
		this.registrationsDone = value;
	}

	/**
	 * Gets the value of the safetyPeriodExpirationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getSafetyPeriodExpirationDate() {
		return safetyPeriodExpirationDate;
	}

	/**
	 * Sets the value of the safetyPeriodExpirationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setSafetyPeriodExpirationDate(Date value) {
		this.safetyPeriodExpirationDate = value;
	}

	/**
	 * Gets the value of the deviceCounters property.
	 * 
	 * @return possible object is {@link SearchDeviceCountersByPartyIdResp.DeviceCounters }
	 * 
	 */
	public SearchDeviceCountersByPartyIdResp.DeviceCounters getDeviceCounters() {
		return deviceCounters;
	}

	/**
	 * Sets the value of the deviceCounters property.
	 * 
	 * @param value
	 *            allowed object is {@link SearchDeviceCountersByPartyIdResp.DeviceCounters }
	 * 
	 */
	public void setDeviceCounters(SearchDeviceCountersByPartyIdResp.DeviceCounters value) {
		this.deviceCounters = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
	 *         &lt;element name="deviceCounter" type="{}deviceCounterType"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "deviceCounter" })
	public static class DeviceCounters {

		private List<DeviceCounterType> deviceCounter;

		/**
		 * Gets the value of the deviceCounter property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the deviceCounter property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDeviceCounter().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link DeviceCounterType }
		 * 
		 * 
		 */
		public List<DeviceCounterType> getDeviceCounter() {
			if (deviceCounter == null) {
				deviceCounter = new ArrayList<DeviceCounterType>();
			}
			return this.deviceCounter;
		}

	}

}
