//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 03:52:18 PM CEST 
//


package com.accenture.sdp.csmfe.restservices.response.shoppingcart;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.accenture.sdp.csmfe.webservices.response.BaseResp;


/**
 * <p>Java class for GetShoppingCartByIdResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetShoppingCartByIdResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseResp">
 *       &lt;sequence>
 *         &lt;element name="shoppingCart" type="{}shoppingCartType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetShoppingCartByIdResponse", propOrder = {
    "shoppingCart"
})
public class GetShoppingCartByIdResponse
    extends BaseResp
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected ShoppingCartType shoppingCart;

    /**
     * Gets the value of the shoppingCart property.
     * 
     * @return
     *     possible object is
     *     {@link ShoppingCartType }
     *     
     */
    public ShoppingCartType getShoppingCart() {
        return shoppingCart;
    }

    /**
     * Sets the value of the shoppingCart property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShoppingCartType }
     *     
     */
    public void setShoppingCart(ShoppingCartType value) {
        this.shoppingCart = value;
    }

}
