package wsclient.com.accenture.avs.be.ws.accountmgmtservice_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import wsclient.accountmgmt.avs.accenture.ports.accountmgmtservice_v1.AccountMgmtPort;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.9-redhat-2
 * 2013-05-03T17:07:55.597+02:00
 * Generated source version: 2.4.9-redhat-2
 * 
 */
@WebServiceClient(name = "AccountMgmtService", 
                  wsdlLocation = "file:/development/wsAccenture/AMS/WebContent/wsdl/AccountManagement/AVS_AccountManagement_Service.wsdl",
                  targetNamespace = "http://ws.be.avs.accenture.com/AccountMgmtService-v1") 
public class AccountMgmtService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.be.avs.accenture.com/AccountMgmtService-v1", "AccountMgmtService");
    public final static QName AccountMgmtServicePort = new QName("http://ws.be.avs.accenture.com/AccountMgmtService-v1", "AccountMgmtServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/development/wsAccenture/AMS/WebContent/wsdl/AccountManagement/AVS_AccountManagement_Service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccountMgmtService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/development/wsAccenture/AMS/WebContent/wsdl/AccountManagement/AVS_AccountManagement_Service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccountMgmtService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountMgmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountMgmtService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     *
     * @return
     *     returns AccountMgmtPort
     */
    @WebEndpoint(name = "AccountMgmtServicePort")
    public AccountMgmtPort getAccountMgmtServicePort() {
        return super.getPort(AccountMgmtServicePort, AccountMgmtPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountMgmtPort
     */
    @WebEndpoint(name = "AccountMgmtServicePort")
    public AccountMgmtPort getAccountMgmtServicePort(WebServiceFeature... features) {
        return super.getPort(AccountMgmtServicePort, AccountMgmtPort.class, features);
    }

}
