insert into sys_parameters(PARAM_GROUP,PARAM_NAME,PARAM_VALUE,PARAM_LABEL,PARAM_PLATFORM,PARAM_ORDER,PARAM_DESCRIPTION,UPDATE_DATE,CREATION_DATE,PARAM_TYPE) 
values	('costpa','BPOINT_IN_PANIC','N','BPOINT_IN_PANIC','TDB','1','BPOINT_IN_PANIC',now(),now(),'STRING');
