<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:tns="http://ws.be.avs.accenture.com/PackageIngestorService-v1" 
xmlns:ns="http://ports.accenture.avs.packageingestor/PackageIngestorService-v1" 
targetNamespace="http://ws.be.avs.accenture.com/PackageIngestorService-v1">
	<wsdl:import namespace="http://ports.accenture.avs.packageingestor/PackageIngestorService-v1" location="AVS_PackageIngestor_Message.wsdl"/>
	<wsdl:binding name="SoapBinding" type="ns:PackageIngestorPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="PackageIngestorService">
			<soap:operation soapAction="http://ws.be.avs.accenture.com/PackageIngestorService-v1/PackageIngestorRequest" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="PackageIngestorService">
		<wsdl:port name="PackageIngestorServicePort" binding="tns:SoapBinding">
			<soap:address location="PackageIngestorService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>