<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:tns="http://ports.accenture.avs.packageingestor/PackageIngestorService-v1" 
xmlns:ns="http://accenture.avs.packageingestor.types" 
targetNamespace="http://ports.accenture.avs.packageingestor/PackageIngestorService-v1">
	<wsdl:types>
		<xs1:schema xmlns:prf="http://accenture.avs.packageingestor.types" xmlns:xs1="http://www.w3.org/2001/XMLSchema">
			<xs1:import namespace="http://accenture.avs.packageingestor.types" schemaLocation="AVS_PackageIngestor_Types.xsd"/>
		</xs1:schema>
	</wsdl:types>
	<wsdl:message name="PackageIngestorRequest">
		<wsdl:part name="PackageIngestorRequest" element="ns:PackageIngestorRequest"/>
	</wsdl:message>
	<wsdl:message name="PackageIngestorResponse">
		<wsdl:part name="PackageIngestorResponse" element="ns:PackageIngestorResponse"/>
	</wsdl:message>
	<wsdl:portType name="PackageIngestorPort">
		<wsdl:operation name="PackageIngestorService">
			<wsdl:input message="tns:PackageIngestorRequest"/>
			<wsdl:output message="tns:PackageIngestorResponse"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>