//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 09:27:19 AM CET 
//

package com.accenture.sdp.devicemetering.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for eventType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventTypeId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="deviceUUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resultDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventType")
@Entity
@Table(name = "SDP_DEVICE_TRACING")
public class EventType implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID")
	private long id;

	@Column(name = "EVENT_TYPE_ID")
	private long eventTypeId;
	@Column(name = "DEVICE_UUID")
	private String deviceUUID;
	@Column(name = "PARTY_ID")
	private Long partyId;

	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EVENT_TIMESTAMP")
	private Date timestamp;
	@XmlElement(required = true)
	@Column(name = "RESULT")
	private String result;
	@XmlElement(required = true)
	@Column(name = "RESULT_DESCRIPTION")
	private String resultDescription;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/**
	 * Gets the value of the eventTypeId property.
	 * 
	 */
	public long getEventTypeId() {
		return eventTypeId;
	}

	/**
	 * Sets the value of the eventTypeId property.
	 * 
	 */
	public void setEventTypeId(long value) {
		this.eventTypeId = value;
	}

	/**
	 * Gets the value of the deviceUUID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceUUID() {
		return deviceUUID;
	}

	/**
	 * Sets the value of the deviceUUID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceUUID(String value) {
		this.deviceUUID = value;
	}

	/**
	 * Gets the value of the partyId property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getPartyId() {
		return partyId;
	}

	/**
	 * Sets the value of the partyId property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setPartyId(Long value) {
		this.partyId = value;
	}

	/**
	 * Gets the value of the timestamp property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * Sets the value of the timestamp property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setTimestamp(Date value) {
		this.timestamp = value;
	}

	/**
	 * Gets the value of the result property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResult() {
		return result;
	}

	/**
	 * Sets the value of the result property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResult(String value) {
		this.result = value;
	}

	/**
	 * Gets the value of the resultDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResultDescription() {
		return resultDescription;
	}

	/**
	 * Sets the value of the resultDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResultDescription(String value) {
		this.resultDescription = value;
	}

}
